localhub/notifications/urls.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    notification_delete_all_view,
    notification_delete_view,
    notification_list_view,
    notification_mark_all_read_view,
    notification_mark_read_view,
    service_worker_view,
    subscribe_view,
    unsubscribe_view,
)

app_name = "notifications"

urlpatterns = [
    path("", notification_list_view, name="list"),
    path("service-worker.js", service_worker_view, name="service_worker"),
    path("~subscribe/", subscribe_view, name="subscribe"),
    path("~unsubscribe/", unsubscribe_view, name="unsubscribe"),
    path("<int:pk>/~delete/", notification_delete_view, name="delete"),
    path("<int:pk>/~mark-read/", notification_mark_read_view, name="mark_read"),
    path("~delete-all/", notification_delete_all_view, name="delete_all"),
    path("~mark-all-read/", notification_mark_all_read_view, name="mark_all_read",),
]

localhub/private_messages/urls.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path, re_path

from localhub.users.urls import USERNAME_RE

from .views import (
    inbox_view,
    message_bookmark_view,
    message_create_view,
    message_delete_view,
    message_detail_view,
    message_follow_up_view,
    message_mark_all_read_view,
    message_mark_read_view,
    message_remove_bookmark_view,
    message_reply_view,
    outbox_view,
)

app_name = "private_messages"

urlpatterns = [
    path("inbox/", inbox_view, name="inbox"),
    path("outbox/", outbox_view, name="outbox"),
    path("~/mark-read/", message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", message_detail_view, name="message_detail"),
    path(
        "message/<int:pk>/~follow-up/", message_follow_up_view, name="message_follow_up"
    ),
    path("message/<int:pk>/~reply/", message_reply_view, name="message_reply"),
    path("message/<int:pk>/~delete/", message_delete_view, name="message_delete"),
    path("message/<int:pk>/~read/", message_mark_read_view, name="message_mark_read"),
    path(
        "message/<int:pk>/~bookmark/", message_bookmark_view, name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        message_remove_bookmark_view,
        name="message_remove_bookmark",
    ),
    re_path(USERNAME_RE + r"~send/$", message_create_view, name="message_create"),
]

localhub/urls.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from localhub.activities.views.streams import activity_stream_view
from localhub.communities.views import (
    community_list_view,
    community_not_found_view,
    community_sidebar_view,
    community_welcome_view,
)
from localhub.users.views import (
    darkmode_toggle_view,
    user_delete_view,
    user_update_view,
)

urlpatterns = [
    # Local
    path("", view=activity_stream_view, name="activity_stream"),
    path("", include("localhub.activities.urls")),
    path("bookmarks/", include("localhub.bookmarks.urls")),
    path("comments/", include("localhub.comments.urls")),
    path("events/", include("localhub.events.urls")),
    path("flags/", include("localhub.flags.urls")),
    path("invites/", include("localhub.invites.urls")),
    path("join-requests/", include("localhub.join_requests.urls")),
    path("notifications/", include("localhub.notifications.urls")),
    path("favorites/", include("localhub.likes.urls")),
    path("messages/", include("localhub.private_messages.urls")),
    path("photos/", include("localhub.photos.urls")),
    path("polls/", include("localhub.polls.urls")),
    path("posts/", include("localhub.posts.urls")),
    path("people/", include("localhub.users.urls")),
    path("community/", include("localhub.communities.urls")),
    path("communities/", community_list_view, name="community_list"),
    path("account/~update", user_update_view, name="user_update"),
    path("account/~delete", user_delete_view, name="user_delete"),
    path("~toggle-darkmode/", darkmode_toggle_view, name="darkmode_toggle"),
    path("welcome/", view=community_welcome_view, name="community_welcome"),
    path("sidebar/", view=community_sidebar_view, name="community_sidebar"),
    path("not-found/", view=community_not_found_view, name="community_not_found"),
    # Third-party
    path("account/", include("allauth.urls")),
    path("markdownx/", include("markdownx.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

# silk
if "silk" in settings.INSTALLED_APPS:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:

    # debug toolbar
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # static views
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # allow preview/debugging of error views in development
    urlpatterns += [
        path("errors/400/", TemplateView.as_view(template_name="400.html")),
        path("errors/403/", TemplateView.as_view(template_name="403.html")),
        path("errors/404/", TemplateView.as_view(template_name="404.html")),
        path("errors/405/", TemplateView.as_view(template_name="405.html")),
        path("errors/500/", TemplateView.as_view(template_name="500.html")),
        path("errors/csrf/", TemplateView.as_view(template_name="403_csrf.html")),
    ]

localhub/notifications/models.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

import json

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from model_utils.models import TimeStampedModel
from pywebpush import WebPushException, webpush

from localhub.communities.models import Community


class NotificationQuerySet(models.QuerySet):
    def for_community(self, community):
        """Filter notifications for a community, including
        only those with actors who are active members.

        Args:
            community (Community)

        Returns:
            QuerySet
        """

        return self.filter(
            community=community,
            actor__membership__community=community,
            actor__membership__active=True,
            actor__is_active=True,
        )

    def exclude_blocked_actors(self, recipient):
        """Exclude all notifications with actors blocked by the recipient.

        Args:
            recipient (User): notification recipient

        Returns:
            QuerySet
        """

        return self.exclude(actor__in=recipient.blocked.all())

    def for_recipient(self, recipient):
        """Return all notifications for a recipient

        Args:
            recipient (User): notification recipient

        Returns:
            QuerySet
        """

        return self.filter(recipient=recipient)

    def unread(self):
        """Return all notifications with is_read=False

        Returns:
            QuerySet
        """

        return self.filter(is_read=False)

    def mark_read(self):
        """Marks all notifications read if they are unread.

        Returns:
            int -- number updated
        """

        return self.unread().update(is_read=True)


class Notification(TimeStampedModel):
    """
    If you define a model as a content_object of this class, you must register
    the model with a Adapter subclass in a notifications module
    under the model app.
    """

    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="+"
    )
    recipient = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="+"
    )
    community = models.ForeignKey(Community, on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    verb = models.CharField(max_length=30)
    is_read = models.BooleanField(default=False)

    objects = NotificationQuerySet.as_manager()

    class Meta:
        indexes = [
            models.Index(
                fields=["content_type", "object_id", "created", "-created", "is_read",]
            )
        ]


class PushSubscription(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    endpoint = models.TextField()
    auth = models.TextField()
    p256dh = models.TextField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "auth", "p256dh", "community"],
                name="unique_push_notification",
            )
        ]

    def push(self, payload, ttl=0):
        """Sends push notification.
        If sub has expired, will delete the instance.

        This should probably be called asynchronously e.g. in celery.

        Args:
            payload (dict): webpush payload e.g. "header", "body", "url"
            ttl (int, optional): time to live (default: 0)

        Returns:
            bool: if webpush succeeds

        Raises:
            WebPushException
        """

        subscription_info = {
            "endpoint": self.endpoint,
            "keys": {"auth": self.auth, "p256dh": self.p256dh},
        }

        vapid_creds = {}
        if settings.VAPID_PRIVATE_KEY:
            vapid_creds["vapid_private_key"] = settings.VAPID_PRIVATE_KEY
        if settings.VAPID_ADMIN_EMAIL:
            vapid_creds["vapid_claims"] = {
                "sub": f"mailto:{settings.VAPID_ADMIN_EMAIL}"
            }

        try:
            webpush(
                subscription_info=subscription_info,
                data=json.dumps(payload),
                ttl=ttl,
                **vapid_creds,
            )
            return True
        except WebPushException as e:
            if e.response.status_code == 410:  # timeout
                self.delete()
            else:
                raise e

        return False

localhub/private_messages/forms.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("message",)
        labels = {"message": _("Send Message")}

localhub/notifications/views/notifications.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from vanilla import DeleteView, GenericModelView, ListView

from localhub.communities.views import CommunityRequiredMixin

from ..models import Notification
from ..signals import notification_read


class NotificationQuerySetMixin(CommunityRequiredMixin):
    def get_queryset(self):
        return Notification.objects.for_community(self.request.community).for_recipient(
            self.request.user
        )


class UnreadNotificationQuerySetMixin(NotificationQuerySetMixin):
    def get_queryset(self):
        return super().get_queryset().unread()


class NotificationSuccessRedirectMixin:
    def get_success_url(self):
        return reverse("notifications:list")


class NotificationListView(NotificationQuerySetMixin, ListView):
    paginate_by = settings.LONG_PAGE_SIZE
    template_name = "notifications/notification_list.html"
    model = Notification

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .exclude_blocked_actors(self.request.user)
            .prefetch_related("content_object")
            .select_related("actor", "content_type")
            .order_by("is_read", "-created")
        )

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["is_unread_notifications"] = (
            self.get_queryset().filter(is_read=False).exists()
        )
        return data


notification_list_view = NotificationListView.as_view()


class NotificationMarkAllReadView(
    UnreadNotificationQuerySetMixin, NotificationSuccessRedirectMixin, GenericModelView,
):
    def post(self, request, *args, **kwargs):
        qs = self.get_queryset()
        [
            notification_read.send(
                sender=notification.content_object.__class__,
                instance=notification.content_object,
            )
            for notification in qs.prefetch_related("content_object")
        ]
        qs.update(is_read=True)
        return HttpResponseRedirect(self.get_success_url())


notification_mark_all_read_view = NotificationMarkAllReadView.as_view()


class NotificationMarkReadView(
    UnreadNotificationQuerySetMixin, NotificationSuccessRedirectMixin, GenericModelView,
):
    def post(self, request, *args, **kwargs):
        notification = self.get_object()
        notification.is_read = True
        notification.save()

        notification_read.send(
            sender=notification.content_object.__class__,
            instance=notification.content_object,
        )

        return HttpResponseRedirect(self.get_success_url())


notification_mark_read_view = NotificationMarkReadView.as_view()


class NotificationDeleteAllView(
    NotificationQuerySetMixin, NotificationSuccessRedirectMixin, GenericModelView,
):
    def delete(self, request):
        self.get_queryset().delete()
        return HttpResponseRedirect(self.get_success_url())

    def post(self, request):
        return self.delete(request)


notification_delete_all_view = NotificationDeleteAllView.as_view()


class NotificationDeleteView(
    NotificationQuerySetMixin, NotificationSuccessRedirectMixin, DeleteView
):

    ...


notification_delete_view = NotificationDeleteView.as_view()

localhub/notifications/views/webpush.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

import json

from django.conf import settings
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, JsonResponse
from django.views.generic import View
from vanilla import TemplateView

from localhub.communities.views import CommunityRequiredMixin

from ..models import PushSubscription


class BasePushSubscriptionView(CommunityRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            json_body = json.loads(request.body.decode("utf-8"))

            data = {"endpoint": json_body["endpoint"]}
            keys = json_body["keys"]
            data["auth"] = keys["auth"]
            data["p256dh"] = keys["p256dh"]

        except (ValueError, KeyError):
            return HttpResponseBadRequest()

        return self.handle_action(request, **data)

    def handle_action(self, request, auth, p256dh, endpoint):
        raise NotImplementedError


class ServiceWorkerView(TemplateView):
    """
    Returns template containing serviceWorker JS, can't use
    static as must always be under domain. We can also pass
    in server specific settings.
    """

    template_name = "notifications/service_worker.js"

    def get(self, request):
        response = super().get(request)
        response["Content-Type"] = "application/javascript"
        return response

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["vapid_public_key"] = settings.VAPID_PUBLIC_KEY
        return data


service_worker_view = ServiceWorkerView.as_view()


class SubscribeView(BasePushSubscriptionView):
    def handle_action(self, request, auth, p256dh, endpoint):

        try:
            PushSubscription.objects.get_or_create(
                auth=auth,
                p256dh=p256dh,
                endpoint=endpoint,
                user=request.user,
                community=request.community,
            )
        except IntegrityError:
            pass  # dupe, ignore

        return JsonResponse({"message": "ok"}, status=201)


subscribe_view = SubscribeView.as_view()


class UnsubscribeView(BasePushSubscriptionView):
    def handle_action(self, request, auth, p256dh, endpoint):

        PushSubscription.objects.filter(
            auth=auth,
            p256dh=p256dh,
            endpoint=endpoint,
            user=request.user,
            community=request.community,
        ).delete()

        return JsonResponse({"message": "ok"}, status=200)


unsubscribe_view = UnsubscribeView.as_view()

templates/private_messages/includes/email_settings.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}

<p class="toast text-center my-2 d-hide"
   data-controller="cookie-notice"
   data-cookie-notice-name="direct-message-emails">
  <button class="btn btn-clear float-right" data-action="cookie-notice#accept"></button>
  {% url 'user_update' as user_settings_url %}
  {% blocktrans %}You can enable email notifications for new messages <a href="{{ user_settings_url }}">in your settings</a>.{% endblocktrans %}
</p>

templates/private_messages/includes/message.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load account %}
{% load activities_tags %}

<div class="card mb-2{% if is_sender %} bg-gray{% endif %} message"
     id="message-{{ message.id }}">
  <div class="card-header">
    <div class="card-subtitle h6 {% if is_unread %}text-bold{% endif %}">
      {% include "users/includes/chip.html" with profile=message.sender profile_url=sender_url %}
      <span class="timesince">
        {% trans "to" %}
      </span>
      {% include "users/includes/chip.html" with profile=message.recipient profile_url=recipient_url %}
      <span class="timesince">
        {% blocktrans with created=message.created|timesince %}
        {{ created }} ago
        {% endblocktrans %}
      </span>
      {% if is_unread %}
      <div class="chip bg-primary">{% trans "New" %}</div>
      {% endif %}
    </div>
  </div>
  <div class="card-body">
    {% collapsable is_detail %}
    <div class="markdown-content mt-1">
      {{ message.message.markdown|strip_external_images:user }}
    </div>
    {% endcollapsable %}
  </div>
  <div class="card-footer">
    <div class="d-flex align-center mt-1">
      <div class="dropdown mr-2"
           data-controller="toggle">
        <a class="btn btn-sm dropdown-toggle"
           tabindex="0">
          {% trans "Actions" %}<i class="icon icon-caret"></i>
        </a>
        <ul class="menu">
          {% if is_recipient and not message.read %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_mark_read' message.id %}"
               class="d-hide"
               data-controller="js-toggle ajax"
               data-action="ajax#post"
               data-ajax-redirect="{{ request.get_full_path }}">{% trans "Mark As Read" %}</a>
          </li>
          {% endif %}

          <li class="menu-item">
            <a href="{% url 'private_messages:message_bookmark' message.id %}"
               {% if message.has_bookmarked %}
               class="d-hide"
               data-js-toggle-ignore
               {% endif %}
               data-controller="js-toggle ajax"
               data-target="toggle.togglable"
               data-toggle-target="bookmark"
               data-ajax-redirect="none"
               data-action="ajax#post toggle#toggle">{% trans "Bookmark" %}</a>
            <a href="{% url 'private_messages:message_remove_bookmark' message.id %}"
               {% if not message.has_bookmarked %}
               class="d-hide"
               data-js-toggle-ignore
               {% endif %}
               data-controller="js-toggle ajax"
               data-target="toggle.togglable"
               data-toggle-target="bookmark"
               data-ajax-redirect="none"
               data-action="ajax#post toggle#toggle"><s>{% trans "Bookmark" %}</s></a>
          </li>

          {% if can_reply %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_reply' message.id %}">
              {% trans "Reply" %}
            </a>
          </li>
          {% elif can_follow_up %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_follow_up' message.id %}">
              {% trans "Follow-Up" %}
            </a>
          </li>
          {% endif %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_delete' message.id %}"
               data-controller="ajax confirm"
               data-action="confirm#check ajax#post"
               data-ajax-redirect="{{ post_delete_redirect|default:request.get_full_path }}"
               data-confirm-header="{% trans 'Delete Message' %}"
               data-confirm-body="{% trans "Are you sure you want to delete this message? Replies to this message will not be deleted. The message may still be available to the other person." %}">{% trans "Delete" %}</a>

          </li>
        </ul>
      </div>
      {% if not is_detail %}
      <div class="actions">
        <a href="{{ message_url }}">{% trans "Link" %}</a>
        {% if parent %}
        <a href="{{ parent_url }}">{% trans "Parent" %}</a>
        {% endif %}
      </div>
      {% endif %}
    </div>
    <div class="clearfix"></div>
  </div>
</div>

templates/private_messages/includes/message_list.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load private_messages_tags %}

{% if object_list %}
{% for message in object_list %}
{% show_message user community message %}
{% endfor %}
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}

templates/private_messages/includes/notification.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if verb == "reply" %}
{% blocktrans %}
{{ actor_display }} has replied to your <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% elif verb == "follow_up" %}
{% blocktrans %}
{{ actor_display }} has sent you a <a href="{{ object_url }}">follow-up</a> to one of their messages.
{% endblocktrans %}
{% else %}
{% blocktrans %}
{{ actor_display }} has sent you a <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% endif %}