localhub/comments/urls.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    comment_bookmark_view,
    comment_delete_view,
    comment_detail_view,
    comment_dislike_view,
    comment_flag_view,
    comment_like_view,
    comment_list_view,
    comment_remove_bookmark_view,
    comment_reply_view,
    comment_update_view,
)

app_name = "comments"


urlpatterns = [
    path("", comment_list_view, name="list"),
    path("<int:pk>/", comment_detail_view, name="detail"),
    path("<int:pk>/~update/", comment_update_view, name="update"),
    path("<int:pk>/~delete/", comment_delete_view, name="delete"),
    path("<int:pk>/~like/", comment_like_view, name="like"),
    path("<int:pk>/~bookmark/", comment_bookmark_view, name="bookmark"),
    path(
        "<int:pk>/~bookmark/remove/",
        comment_remove_bookmark_view,
        name="remove_bookmark",
    ),
    path("<int:pk>/~dislike/", comment_dislike_view, name="dislike"),
    path("<int:pk>/~flag/", comment_flag_view, name="flag"),
    path("<int:pk>/~reply/", comment_reply_view, name="reply"),
]

localhub/urls.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from localhub.activities.views.streams import activity_stream_view
from localhub.communities.views import (
    community_list_view,
    community_not_found_view,
    community_sidebar_view,
    community_welcome_view,
)
from localhub.users.views import (
    darkmode_toggle_view,
    user_delete_view,
    user_update_view,
)

urlpatterns = [
    # Local
    path("", view=activity_stream_view, name="activity_stream"),
    path("", include("localhub.activities.urls")),
    path("bookmarks/", include("localhub.bookmarks.urls")),
    path("comments/", include("localhub.comments.urls")),
    path("events/", include("localhub.events.urls")),
    path("flags/", include("localhub.flags.urls")),
    path("invites/", include("localhub.invites.urls")),
    path("join-requests/", include("localhub.join_requests.urls")),
    path("notifications/", include("localhub.notifications.urls")),
    path("favorites/", include("localhub.likes.urls")),
    path("messages/", include("localhub.private_messages.urls")),
    path("photos/", include("localhub.photos.urls")),
    path("polls/", include("localhub.polls.urls")),
    path("posts/", include("localhub.posts.urls")),
    path("people/", include("localhub.users.urls")),
    path("community/", include("localhub.communities.urls")),
    path("communities/", community_list_view, name="community_list"),
    path("account/~update", user_update_view, name="user_update"),
    path("account/~delete", user_delete_view, name="user_delete"),
    path("~toggle-darkmode/", darkmode_toggle_view, name="darkmode_toggle"),
    path("welcome/", view=community_welcome_view, name="community_welcome"),
    path("sidebar/", view=community_sidebar_view, name="community_sidebar"),
    path("not-found/", view=community_not_found_view, name="community_not_found"),
    # Third-party
    path("account/", include("allauth.urls")),
    path("markdownx/", include("markdownx.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

# silk
if "silk" in settings.INSTALLED_APPS:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:

    # debug toolbar
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # static views
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # allow preview/debugging of error views in development
    urlpatterns += [
        path("errors/400/", TemplateView.as_view(template_name="400.html")),
        path("errors/403/", TemplateView.as_view(template_name="403.html")),
        path("errors/404/", TemplateView.as_view(template_name="404.html")),
        path("errors/405/", TemplateView.as_view(template_name="405.html")),
        path("errors/500/", TemplateView.as_view(template_name="500.html")),
        path("errors/csrf/", TemplateView.as_view(template_name="403_csrf.html")),
    ]

localhub/users/urls.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path, re_path

from .views import (
    blocked_user_list_view,
    follower_user_list_view,
    following_user_list_view,
    member_list_view,
    user_autocomplete_list_view,
    user_block_view,
    user_comment_list_view,
    user_follow_view,
    user_message_list_view,
    user_stream_view,
    user_unblock_view,
    user_unfollow_view,
)

app_name = "users"

USERNAME_RE = r"^(?P<username>[\w.@+-]+)/"

urlpatterns = [
    path("autocomplete/", view=user_autocomplete_list_view, name="autocomplete_list",),
    path("members/", view=member_list_view, name="member_list"),
    path("following/", view=following_user_list_view, name="following_list"),
    path("followers/", view=follower_user_list_view, name="follower_list"),
    path("blocked/", view=blocked_user_list_view, name="blocked_list"),
    re_path(USERNAME_RE + r"follow/$", view=user_follow_view, name="follow"),
    re_path(USERNAME_RE + r"unfollow/$", view=user_unfollow_view, name="unfollow"),
    re_path(USERNAME_RE + r"block/$", view=user_block_view, name="block"),
    re_path(USERNAME_RE + r"unblock/$", view=user_unblock_view, name="unblock"),
    re_path(USERNAME_RE + r"comments/$", view=user_comment_list_view, name="comments"),
    re_path(USERNAME_RE + r"messages/$", view=user_message_list_view, name="messages"),
    re_path(USERNAME_RE + r"$", view=user_stream_view, name="activities"),
]

localhub/comments/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        labels = {"content": _("Comment")}

localhub/comments/views.py
# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.contrib import messages
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext as _
from rules.contrib.views import PermissionRequiredMixin
from vanilla import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    GenericModelView,
    ListView,
    UpdateView,
)

from localhub.bookmarks.models import Bookmark
from localhub.communities.views import CommunityRequiredMixin
from localhub.flags.forms import FlagForm
from localhub.likes.models import Like
from localhub.views import SearchMixin

from .forms import CommentForm
from .models import Comment


class CommentQuerySetMixin(CommunityRequiredMixin):
    def get_queryset(self):
        return Comment.objects.for_community(self.request.community).select_related(
            "owner", "community", "parent", "parent__owner", "parent__community",
        )


class BaseCommentListView(CommentQuerySetMixin, ListView):
    paginate_by = settings.DEFAULT_PAGE_SIZE

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_common_annotations(self.request.user, self.request.community)
            .exclude_blocked_users(self.request.user)
            .exclude_deleted()
            .prefetch_related("content_object")
        )


class CommentListView(SearchMixin, BaseCommentListView):

    template_name = "comments/comment_list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by("-created")


comment_list_view = CommentListView.as_view()


class CommentDetailView(CommentQuerySetMixin, DetailView):
    model = Comment

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .exclude_deleted(self.request.user)
            .select_related("editor")
            .with_common_annotations(self.request.user, self.request.community)
        )

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.object.get_notifications().for_recipient(
            self.request.user
        ).unread().update(is_read=True)
        return response

    def get_flags(self):
        return self.object.get_flags().select_related("user").order_by("-created")

    def get_replies(self):
        if self.object.deleted:
            return self.get_queryset().none()
        return self.get_queryset().filter(parent=self.object).order_by("created")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.user.has_perm(
            "communities.moderate_community", self.request.community
        ):
            data["flags"] = self.get_flags()
        data["replies"] = self.get_replies()
        return data


comment_detail_view = CommentDetailView.as_view()


class CommentUpdateView(
    PermissionRequiredMixin, CommentQuerySetMixin, UpdateView,
):
    form_class = CommentForm
    model = Comment
    permission_required = "comments.change_comment"

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.editor = self.request.user
        comment.edited = timezone.now()
        comment.save()

        comment.notify_on_update()

        messages.success(self.request, _("Comment has been updated"))
        return redirect(comment.content_object)


comment_update_view = CommentUpdateView.as_view()


class CommentDeleteView(
    PermissionRequiredMixin, CommentQuerySetMixin, DeleteView,
):
    permission_required = "comments.delete_comment"
    template_name = "comments/comment_confirm_delete.html"

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        if self.request.user != comment.owner:
            comment.soft_delete()
            comment.notify_on_delete(self.request.user)
        else:
            comment.delete()

        messages.success(request, _("Comment has been deleted"))
        return redirect(comment.content_object)


comment_delete_view = CommentDeleteView.as_view()


class CommentBookmarkView(
    PermissionRequiredMixin, CommentQuerySetMixin, GenericModelView,
):
    permission_required = "comments.bookmark_comment"

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        try:
            Bookmark.objects.create(
                user=request.user, community=request.community, content_object=comment,
            )
        except IntegrityError:
            pass
        if request.is_ajax():
            return HttpResponse(status=204)
        return redirect(comment)


comment_bookmark_view = CommentBookmarkView.as_view()


class CommentRemoveBookmarkView(CommentQuerySetMixin, GenericModelView):
    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        Bookmark.objects.filter(user=request.user, comment=comment).delete()
        if request.is_ajax():
            return HttpResponse(status=204)
        return redirect(comment)

    def delete(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


comment_remove_bookmark_view = CommentRemoveBookmarkView.as_view()


class CommentLikeView(
    PermissionRequiredMixin, CommentQuerySetMixin, GenericModelView,
):
    permission_required = "comments.like_comment"

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        try:
            Like.objects.create(
                user=request.user,
                community=request.community,
                recipient=comment.owner,
                content_object=comment,
            ).notify()
        except IntegrityError:
            pass
        if request.is_ajax():
            return HttpResponse(status=204)
        return redirect(comment)


comment_like_view = CommentLikeView.as_view()


class CommentDislikeView(CommentQuerySetMixin, GenericModelView):
    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        Like.objects.filter(user=request.user, comment=comment).delete()
        if request.is_ajax():
            return HttpResponse(status=204)
        return redirect(comment)

    def delete(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


comment_dislike_view = CommentDislikeView.as_view()


class CommentFlagView(
    PermissionRequiredMixin, CommentQuerySetMixin, FormView,
):
    form_class = FlagForm
    template_name = "comments/flag_form.html"
    permission_required = "comments.flag_comment"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_has_flagged(self.request.user)
            .exclude(has_flagged=True)
        )

    def get_permission_object(self):
        return self.comment

    @cached_property
    def comment(self):
        return get_object_or_404(self.get_queryset(), pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["comment"] = self.comment
        return data

    def form_valid(self, form):
        flag = form.save(commit=False)
        flag.content_object = self.comment
        flag.community = self.request.community
        flag.user = self.request.user
        flag.save()

        flag.notify()

        messages.success(
            self.request, _("This comment has been flagged to the moderators")
        )
        return redirect(self.comment.content_object)


comment_flag_view = CommentFlagView.as_view()


class CommentReplyView(
    CommentQuerySetMixin, PermissionRequiredMixin, CreateView,
):
    permission_required = "comments.reply_to_comment"
    model = Comment
    form_class = CommentForm

    def get_permission_object(self):
        return self.parent

    @cached_property
    def parent(self):
        return get_object_or_404(self.get_queryset(), pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["parent"] = self.parent
        return data

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.parent = self.parent
        comment.content_object = self.parent.content_object
        comment.owner = self.request.user
        comment.community = self.request.community
        comment.save()

        comment.notify_on_create()
        messages.success(self.request, _("Your comment has been posted"))
        return redirect(comment.content_object)


comment_reply_view = CommentReplyView.as_view()

templates/comments/includes/comment.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load account %}
{% load rules %}
{% load activities_tags %}

<article class="card"
         role="comment"
         id="comment-{{ comment.id }}">
  <div class="card-header">
    {% if with_activity %}
    <div class="card-title h6">
      {% with content_object=comment.content_object %}
      {% if content_object and not content_object.deleted %}
      <a href="{{ comment.content_object.get_absolute_url }}">{{ comment.content_object }}</a>
      {% else %}
      {% trans "[Deleted]" %}
      {% endif %}
      {% endwith %}
    </div>
    {% endif %}
    {% has_perm "communities.moderate_community" user community as can_moderate_community %}
    {% if comment.is_flagged and can_moderate_community %}
    <div class="toast toast-info text-center mb-2">
      <a href="{{ comment.get_absolute_url }}">{% trans "This comment has been flagged" %}</a>
    </div>
    {% endif %}

    <div class="card-title h6">
      {% url 'users:comments' comment.owner.username as owner_url %}
      {% include "activities/includes/timesince.html" with profile_url=owner_url timestamp=comment.created owner=comment.owner %}
    </div>
  </div>
  {% if comment.is_blocked %}
  <div class="card-body"
       data-controller="toggle">
    <strong>{% trans "You have blocked this user." %}</strong>
    <div class="markdown-content d-hide"
         data-target="toggle.togglable"
         data-toggle-target="blocked-comment">
      {{ comment.content.markdown|strip_external_images:user }}
    </div>
    <div class="actions">
      <a href="#"
         data-target="toggle.togglable"
         data-toggle-target="blocked-comment"
         data-action="toggle#toggle">{% trans "View Comment" %}</a>
    </div>
  </div>
  {% else %}
  <div class="card-body">
    {% if comment.deleted %}
    <p>{% blocktrans %}This comment has been deleted by a community moderator{% endblocktrans %}</p>
    {% endif %}
    {% if not comment.deleted or comment.owner == user %}
    {% collapsable is_detail %}
    <div class="markdown-content mt-1">
      {{ comment.content.markdown|strip_external_images:user }}
    </div>
    {% endcollapsable %}
    {% endif %}
  </div>
  <div class="card-footer">
    {% if comment.num_likes and comment.owner == user %}
    <div class="info">
      {{ comment.num_likes }}
      {% blocktrans count counter=comment.num_likes %}
      Like
      {% plural %}
      Likes
      {% endblocktrans %}
    </div>
    {% endif %}

    {% if comment.edited %}
    <div class="info">
      {% blocktrans with edited=comment.edited|timesince %}Updated {{ edited }} ago{% endblocktrans %}
    </div>
    {% endif %}
    <div class="d-flex align-center mt-1">
      <div class="dropdown mr-2"
           data-controller="toggle">
        <a class="btn btn-sm dropdown-toggle"
           tabindex="0">
          {% trans "Actions" %}<i class="icon icon-caret"></i>
        </a>
        <ul class="menu">
          {% has_perm "comments.like_comment" user comment as can_like_comment %}
          {% if can_like_comment %}
          <li class="menu-item">
            <a href="{% url 'comments:like' comment.id %}"
               {% if comment.has_liked %}
               class="d-hide"
               data-js-toggle-ignore
               {% endif %}
               data-controller="js-toggle ajax"
               data-target="toggle.togglable"
               data-toggle-target="like"
               data-ajax-redirect="none"
               data-action="ajax#post toggle#toggle">{% trans "Like" %}</a>
            <a href="{% url 'comments:dislike' comment.id %}"
               {% if not comment.has_liked %}
               class="d-hide"
               data-js-toggle-ignore
               {% endif %}
               data-controller="js-toggle ajax"
               data-target="toggle.togglable"
               data-toggle-target="like"
               data-ajax-redirect="none"
               data-action="ajax#post toggle#toggle"><s>{% trans "Like" %}</s></a>
          </li>
          {% endif %}

          {% has_perm "comments.bookmark_comment" user comment as can_bookmark_comment %}
          {% if can_bookmark_comment %}
          <li class="menu-item">
            <a href="{% url 'comments:bookmark' comment.id %}"
               {% if comment.has_bookmarked %}
               class="d-hide"
               data-js-toggle-ignore
               {% endif %}
               data-controller="js-toggle ajax"
               data-target="toggle.togglable"
               data-toggle-target="bookmark"
               data-ajax-redirect="none"
               data-action="ajax#post toggle#toggle">{% trans "Bookmark" %}</a>
            <a href="{% url 'comments:remove_bookmark' comment.id %}"
               {% if not comment.has_bookmarked %}
               class="d-hide"
               data-js-toggle-ignore
               {% endif %}
               data-controller="js-toggle ajax"
               data-target="toggle.togglable"
               data-toggle-target="bookmark"
               data-ajax-redirect="none"
               data-action="ajax#post toggle#toggle"><s>{% trans "Bookmark" %}</s></a>
          </li>
          {% endif %}

          {% has_perm "comments.reply_to_comment" user comment as can_reply %}
          {% if can_reply %}
          <li class="menu-item">
            <a href="{% url 'comments:reply' comment.id %}">{% trans "Reply" %}</a>
          </li>
          {% endif %}

          {% has_perm "comments.flag_comment" user comment as can_flag_comment %}
          {% if can_flag_comment and not comment.has_flagged %}
          <li class="menu-item">
            <a href="{% url 'comments:flag' comment.id %}">
              {% trans "Flag" %}
            </a>
          </li>
          {% endif %}
          {% has_perm "comments.change_comment" user comment as can_change_comment %}

          {% if can_change_comment %}
          <li class="menu-item">
            <a href="{% url 'comments:update' comment.id %}">
              {% trans "Edit" %}
            </a>
          </li>
          {% endif %}
          {% has_perm "comments.delete_comment" user comment as can_delete_comment %}
          {% if can_delete_comment %}
          <li class="menu-item">
            <a href="{% url 'comments:delete' comment.id %}"
               data-controller="ajax confirm"
               data-action="confirm#check ajax#post"
               {% if not is_detail %}
               data-ajax-redirect="{{ request.get_full_path }}"
               {% endif %}
               data-confirm-header="{% trans 'Delete Comment' %}"
               data-confirm-body="{% trans 'Are you sure you want to delete this comment?' %}">
              {% trans "Delete" %}
            </a>
          </li>
          {% endif %}

        </ul>
      </div>
      <div class="actions">
        {% if not is_detail and not comment.deleted %}
        <a href="{{ comment.get_absolute_url }}">{% trans "Link" %}</a>
        {% endif %}
        {% with parent=comment.parent %}
        {% if parent and not parent.deleted and comment.is_parent_owner_member and not is_reply %}
        <a {% spaceless %}
           {% if is_thread %}
           href="#comment-{{ parent.id }}"
           data-turbolinks="false"
           {% else %}
           href="{{ parent.get_absolute_url }}"
           {% endif %}
           {% endspaceless %}>{% trans "Parent" %}</a>
        {% endif %}
        {% endwith %}
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
  {% endif %}
</article>

templates/comments/includes/comment_list.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% for comment in object_list %}
<div class="activity-list-item">
  {% include "comments/includes/comment.html" with with_activity=True %}
</div>
{% empty %}
{% include "includes/empty.html" %}
{% endfor %}
{% include "includes/pagination.html" %}